version: '3'

services:
  furry-octo-winner:
    build:
      context: .
    ports:
    - 8081:8080
    volumes:
      - ./server:/opt/app
    links:
    - postgresql:db
  
  postgresql:
    build:
      context: ./sql
    environment:
    - POSTGRES_USER=funnyApp
    - POSTGRES_PASSWORD=funnyApp
    - POSTGRES_DB=funnyApp
