FROM frekele/gradle

WORKDIR /opt
RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh \
 && chmod +x ./wait-for-it.sh

RUN mkdir -p /opt/app
WORKDIR /opt/app

CMD /opt/wait-for-it.sh app:8080 -t 1000 -- gradle build --continuous --info
